### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by davidanthoff** [spencerlyon2/CompEcon.jl#26]
Is there a chance that this could be registered in Metadata? I have a bunch of stuff that relies on this, and it would be super handy if I could simply add this to a REQUIRE file and wouldn't have to add manual install instructions to a README.

**Comment by sglyon** [comment]
Hey @davidanthoff great to hear that you are using this stuff. I've recently started using it again, which is motivating me to work through some of the low fruit for speeding these routines up. Stay tuned for some performance enhancements!

Just because I'm curious, which parts are you using? This isn't unrelated to your actual question. It is possible that the routines you are using could find a nice home in a package that is already registered.

I'm a bit mixed on what the optimal policy is in this situation. CompEcon.jl started as a port of Miranda and Fackler's Matlab routines, but in many ways has evolved into somewhere I dump tools that I haven't taken the time to integrate anywhere else. What are your feelings on this? Does it deserve its own space in METADATA?

**Comment by davidanthoff** [comment]
I'm actually only using `ckronxi`, nothing else :) I originally thought about just copying just the code for that one function, but the license doesn't work for me...

I think maybe the best thing would be if CompEcon.jl would _just_ be a julia version of the Matlab toolbox. It would just be there to help people convert Matlab stuff. Anything better, more julian, etc. could go into different packages? That would define the scope for this package very clearly...

**Comment by davidanthoff** [comment]
Bump. Any decision on this?

My preference would be that this just gets registered as is, as a direct port of the Matlab toolbox. And then, once you guys feel like it, you can move things out and into other packages. But this is useful as it stands and imho ready to be registered.

**Comment by sglyon** [comment]
That's a good point. I don't see us moving very quickly to find a better home for it so I'll try to get it tagged in the next couple days.

Thanks for following up!

**Comment by davidanthoff** [comment]
Bump :)

**Comment by sglyon** [comment]
Ok so sorry I didn't get to this last week.

I'm working on it now!

(just waiting `Pkg.publish()` to finish running)

**Comment by sglyon** [comment]
Done https://github.com/JuliaLang/METADATA.jl/pull/5738#event-741009404!

**Comment by davidanthoff** [comment]
Thanks, much appreciated!
